# Name for your GitHub Actions workflow
name: GraphQLNomad CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on. "ubuntu-latest" is a good default.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository's code under the $GITHUB_WORKSPACE directory
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up a specific version of Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Installs the script's dependencies
      # It first upgrades pip and then installs requests, colorama, and flake8 for linting.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama flake8

      # Step 4: Lints the code with flake8 to check for style issues and potential errors
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Runs a basic test by executing the script with the --help argument
      # This confirms that the script starts up without any immediate errors.
      - name: Run basic test
        run: python graphqlnomad.py --help
